# Generated by Django 3.0.6 on 2020-05-20 22:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookflixapp', '0007_auto_20200520_1930'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerfilCust',
        ),
    ]
