# Generated by Django 3.0.6 on 2020-05-20 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookflixapp', '0008_delete_perfilcust'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name_plural': 'Perfiles'},
        ),
    ]
