# Generated by Django 3.0.6 on 2020-05-21 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookflixapp', '0009_auto_20200520_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='first_name',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_name',
            field=models.CharField(default='', max_length=20),
        ),
    ]
