# Generated by Django 3.0.6 on 2020-06-14 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookflixapp', '0012_auto_20200520_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='selected',
            field=models.BooleanField(default=True),
        ),
    ]
